In [1]:
import numpy as np
import pandas as pd
import rospkg
import glob
import sys

pkg_name = 'mapless_nav' #'mapless_nav'
pkg_path = rospkg.RosPack().get_path(pkg_name)
files_path = pkg_path + '/scripts/TorchModels/data/'

#print(files_path)
files_names =  files_path+'*.npz'
files = glob.glob(files_names)

for file in files:
    print(file)

/home/devan/GIT/Juskeshino/catkin_ws/src/mapless_navigation/mapless_nav/scripts/TorchModels/data/data_dep1_2025-03-11_14-34-46.npz
/home/devan/GIT/Juskeshino/catkin_ws/src/mapless_navigation/mapless_nav/scripts/TorchModels/data/data_dep1_2025-03-11_14-34-19.npz


In [2]:
npz_file = np.load(files[0],  allow_pickle=True)
print(type(npz_file))
np.set_printoptions(threshold=sys.maxsize)


print(npz_file['data'].shape)
print(npz_file['data'][0].keys())

for sample in npz_file['data']:
    print(sample['labels'])
    print(type(sample['labels']))


<class 'numpy.lib.npyio.NpzFile'>
(131,)
dict_keys(['features', 'labels'])
[0. 0. 0.]
<class 'numpy.ndarray'>
[0. 0. 0.]
<class 'numpy.ndarray'>
[0. 0. 0.]
<class 'numpy.ndarray'>
[0. 0. 0.]
<class 'numpy.ndarray'>
[0. 0. 0.]
<class 'numpy.ndarray'>
[0. 0. 0.]
<class 'numpy.ndarray'>
[0. 0. 0.]
<class 'numpy.ndarray'>
[0. 0. 0.]
<class 'numpy.ndarray'>
[0. 0. 0.]
<class 'numpy.ndarray'>
[0.382 0.    0.217]
<class 'numpy.ndarray'>
[0.382 0.    0.217]
<class 'numpy.ndarray'>
[0.382 0.    0.217]
<class 'numpy.ndarray'>
[0.45  0.    0.328]
<class 'numpy.ndarray'>
[0.45  0.    0.328]
<class 'numpy.ndarray'>
[0.45  0.    0.328]
<class 'numpy.ndarray'>
[0.45  0.    0.328]
<class 'numpy.ndarray'>
[0.45  0.    0.206]
<class 'numpy.ndarray'>
[0.45  0.    0.206]
<class 'numpy.ndarray'>
[0.45  0.    0.184]
<class 'numpy.ndarray'>
[0.45  0.    0.184]
<class 'numpy.ndarray'>
[0.45  0.    0.012]
<class 'numpy.ndarray'>
[0.45  0.    0.012]
<class 'numpy.ndarray'>
[ 0.45   0.    -0.017]
<class 'numpy.n